require "rubygems"
require "rake"
require "rake/testtask"
require "rake/rdoctask"
require "rake/gempackagetask"
require "date"

desc "Run unit tests."
task :default => :test

desc "Test the ruby_amazon_associates library."
Rake::TestTask.new(:test) do |t|
  # t.libs << "test"
  t.test_files = FileList["test/**/*.rb"]
  t.verbose = true
  t.warning = true
end

desc "Generate documentation for the factory_girl plugin."
Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = "rdoc"
  rdoc.title = "ruby_amazon_associates"
  rdoc.options << "--line-numbers" << "--inline-source" << "--main" << "README.textile"
  rdoc.rdoc_files.include("README", "CHANGELOG")
  rdoc.rdoc_files.include("lib/**/*.rb")
end

spec = Gem::Specification.new do |s| 
  s.name = "ruby_amazon_associates"
  s.version = "0.5.4"

  s.specification_version = 2 if s.respond_to? :specification_version=
  
  s.authors = ["Herryanto Siatono", "Dan Pickett"]
  s.email = ["herryanto@pluitsolutions.com, dpickett@enlightsolutions.com"]
  s.homepage = "http://github.com/dpickett/ruby_amazon_associates/tree/master"
  s.platform = Gem::Platform::RUBY
  s.summary = "Generic Amazon Associates Web Service (Formerly ECS) REST API. Supports ECS 4.0."
  s.has_rdoc = true
  s.rdoc_options = ["--line-numbers", "--inline-source", "--main", "README.textile"]
  s.require_path = "lib"
  s.autorequire = "name"
  s.test_files = FileList["{test}/**/*test.rb"].to_a
  s.has_rdoc = true
  s.extra_rdoc_files = ["README", "CHANGELOG"]
  s.add_dependency("hpricot", ">= 0.6")
end

desc "Generate a gemspec file"
task :gemspec do
  File.open("#{spec.name}.gemspec", 'w') do |f|
    f.write spec.to_ruby
  end
end

# Rake::GemPackageTask.new spec do |pkg|
#   pkg.need_tar = true
#   pkg.need_zip = true
# end

desc "Clean files generated by rake tasks"
task :clobber => [:clobber_rdoc, :clobber_package]