require "rubygems"
require "rake"
require "rake/testtask"
require "rake/rdoctask"
require "rake/gempackagetask"
require "date"

desc "Run unit tests."
task :default => :test

desc "Test the amazon_associate library."
Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.test_files = FileList["test/**/*test.rb"]
  t.verbose = true
  t.warning = true
end

desc "Generate documentation for the amazon_associate plugin."
Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = "rdoc"
  rdoc.title = "amazon_associate"
  rdoc.options << "--line-numbers" << "--inline-source" << "--main" << "README.textile"
  rdoc.rdoc_files.include("README.rdoc", "CHANGELOG")
  rdoc.rdoc_files.include("lib/**/*.rb")
end

begin
  require 'jeweler'
  Jeweler::Tasks.new do |gemspec|
    gemspec.name = "amazon_associate"
    gemspec.summary = "Amazon Associates API Interface using Hpricot"
    gemspec.email = "dpickett@enlightsolutions.com"
    gemspec.homepage = "http://github.com/dpickett/amazon_associate"
    gemspec.description = "interfaces with Amazon Associate's API using Hpricot"
    gemspec.authors = ["Dan Pickett"]
  end
rescue LoadError
  puts "Jeweler not available. Install it with: sudo gem install technicalpickles-jeweler -s http://gems.github.com"
end

desc "Clean files generated by rake tasks"
task :clobber => [:clobber_rdoc, :clobber_package]
